title: Eason's Homepage
page-top-title: Yichen Wang
top-section-bg-text: Graph Theory Researcher
home-subtitle: Yichen Wang&ensp;|&ensp;Eason&ensp;|&ensp;汪奕晨
copyright-text: '&copy; Yichen Wang 2025-2027. All Rights Reserved.'
