title: Eason's Homepage
page-top-title: Yichen Wang
top-section-bg-text: Graph Theory Researcher
home-subtitle: Yichen Wang&ensp;|&ensp;Eason
copyright-text: '&copy; Yichen Wang 2025-2027. All Rights Reserved.'
license-credit: 'Template adapted from <a href="https://github.com/Yixin0313/personal-homepage-template">Yixin0313/personal-homepage-template</a>, originally licensed under the <a href="https://github.com/Yixin0313/personal-homepage-template/blob/main/LICENSE">MIT License</a>.'
